<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ArticleSeeder extends Seeder
{
    /**
     * 填充文章数据
     */
    public function run(): void
    {
        $now = Carbon::now();

        // 获取作者ID（默认 root 用户）
        $author = DB::table('admin_users')->where('username', 'root')->first();
        $authorId = $author ? $author->id : 1;

        $articles = [
            // ==================== 公司新闻 (category_id: 6) ====================
            [
                'title' => '公司荣获2025年度行业创新企业称号',
                'slug' => 'company-innovation-award-2025',
                'content' => '<p>近日，在2025年度行业创新企业评选活动中，我公司凭借卓越的技术创新能力和突出的行业贡献，荣获"2025年度行业创新企业"称号。</p><p>此次评选由行业协会联合多家权威机构共同发起，经过严格评审，共有来自全国各地的数百家企业参与角逐。我公司凭借在人工智能、大数据分析等领域的持续投入和创新成果，最终脱颖而出。</p><p>公司CEO表示："这份荣誉是对我们团队多年努力的肯定，更是对未来发展的鞭策。我们将继续加大研发投入，为客户提供更优质的产品和服务。"</p>',
                'excerpt' => '公司荣获2025年度行业创新企业称号，凭借技术创新和行业贡献在数百家企业中脱颖而出。',
                'cover' => '',
                'keywords' => '创新企业,行业奖项,公司荣誉',
                'description' => '公司荣获2025年度行业创新企业称号，展示公司在技术创新和行业贡献方面的卓越成就。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 1,
                'flag_o' => 1,
                'like' => 128,
                'category_id' => 6,
                'author_id' => $authorId,
                'views' => 3580,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => '公司与某知名大学签署战略合作协议',
                'slug' => 'university-strategic-cooperation',
                'content' => '<p>日前，我公司与某知名大学正式签署战略合作协议，双方将在人才培养、科研合作、技术转化等方面开展深度合作。</p><p>根据协议，公司将与大学共建联合实验室，聚焦人工智能、物联网等前沿技术领域。同时，公司将为大学学生提供实习实训机会，大学将为企业员工提供继续教育和培训服务。</p><p>此次合作标志着校企合作进入新阶段，将有力推动产学研一体化发展，为行业发展注入新动能。</p>',
                'excerpt' => '公司与知名大学签署战略合作协议，共建联合实验室，推动产学研一体化发展。',
                'cover' => '',
                'keywords' => '战略合作,校企合作,产学研',
                'description' => '公司与知名大学签署战略合作协议，在人才培养、科研合作等领域开展深度合作。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 86,
                'category_id' => 6,
                'author_id' => $authorId,
                'views' => 2100,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(7),
            ],
            [
                'title' => '公司2025年度总结暨表彰大会圆满举行',
                'slug' => '2025-annual-summary-meeting',
                'content' => '<p>1月15日，公司2025年度总结暨表彰大会在总部隆重举行。公司全体员工齐聚一堂，共同回顾过去一年的奋斗历程，展望新一年的发展蓝图。</p><p>会上，各部门负责人分别汇报了年度工作成果，CEO作了年度工作报告，全面总结了公司在市场拓展、产品研发、团队建设等方面取得的显著成绩。</p><p>大会还对年度优秀员工、优秀团队进行了表彰，颁发了"最佳创新奖"、"最佳服务奖"、"最佳团队奖"等多个奖项。</p>',
                'excerpt' => '公司举行2025年度总结暨表彰大会，回顾年度成果，表彰优秀员工和团队。',
                'cover' => '',
                'keywords' => '年度总结,表彰大会,公司活动',
                'description' => '公司2025年度总结暨表彰大会圆满举行，回顾年度成果并表彰优秀员工与团队。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 56,
                'category_id' => 6,
                'author_id' => $authorId,
                'views' => 1500,
                'sort' => 3,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(15),
            ],
            [
                'title' => '公司新办公室正式启用，办公环境全面升级',
                'slug' => 'new-office-opening',
                'content' => '<p>为满足公司快速发展需要，经过数月的精心筹备，公司新办公室于近日正式启用。新办公室位于市中心核心商务区，总面积超过2000平方米。</p><p>新办公环境采用现代化设计理念，配备了先进的办公设施、多功能会议室、休闲区、健身区等，为员工提供了更加舒适、高效的工作环境。</p><p>公司CEO表示："新办公室的启用是公司发展的重要里程碑，体现了公司对员工的关怀和对未来的信心。"</p>',
                'excerpt' => '公司新办公室正式启用，总面积超2000平方米，办公环境全面升级。',
                'cover' => '',
                'keywords' => '新办公室,办公环境,公司发展',
                'description' => '公司新办公室正式启用，办公环境全面升级，为员工提供更舒适高效的工作空间。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 42,
                'category_id' => 6,
                'author_id' => $authorId,
                'views' => 980,
                'sort' => 4,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(20),
            ],

            // ==================== 行业动态 (category_id: 7) ====================
            [
                'title' => '2026年人工智能行业发展趋势报告',
                'slug' => 'ai-industry-trends-2026',
                'content' => '<p>随着大语言模型技术的快速发展，2026年人工智能行业正迎来新一轮变革。据最新研究报告显示，全球AI市场规模预计将在2026年突破5000亿美元。</p><p>主要趋势包括：大模型向垂直行业深入渗透，AI Agent应用场景不断扩展，边缘AI计算需求快速增长，以及AI安全与治理成为行业焦点。</p><p>业内专家指出，未来三年将是AI技术从实验室走向大规模商业落地的关键期，企业需要积极拥抱变革，加快数字化转型步伐。</p>',
                'excerpt' => '2026年AI行业发展趋势：大模型垂直渗透、AI Agent扩展、边缘计算增长、AI安全治理成焦点。',
                'cover' => '',
                'keywords' => '人工智能,AI趋势,行业报告,大模型',
                'description' => '2026年人工智能行业发展趋势报告，涵盖大模型、AI Agent、边缘计算等热门领域。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 1,
                'flag_o' => 1,
                'like' => 256,
                'category_id' => 7,
                'author_id' => $authorId,
                'views' => 6800,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => '5G+工业互联网融合发展加速推进',
                'slug' => '5g-industrial-internet-integration',
                'content' => '<p>工业和信息化部最新数据显示，我国5G+工业互联网项目已超过1万个，覆盖41个国民经济大类。5G技术在工业领域的应用正从外围辅助环节向核心生产环节渗透。</p><p>在制造业领域，5G+工业互联网实现了远程设备操控、机器视觉质检、无人智能巡检等典型应用场景的规模化落地。在采矿、电力、港口等行业，5G技术的应用也取得了显著成效。</p><p>预计到2026年底，5G+工业互联网融合应用将进一步深化，为我国制造业高质量发展提供有力支撑。</p>',
                'excerpt' => '我国5G+工业互联网项目超1万个，覆盖41个行业大类，应用正加速向核心生产环节渗透。',
                'cover' => '',
                'keywords' => '5G,工业互联网,智能制造,数字化转型',
                'description' => '5G+工业互联网融合发展加速推进，项目超1万个覆盖41个行业大类。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 168,
                'category_id' => 7,
                'author_id' => $authorId,
                'views' => 4200,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(5),
            ],
            [
                'title' => '云计算市场持续增长，边缘计算成为新热点',
                'slug' => 'cloud-computing-edge-computing-trends',
                'content' => '<p>据国际市场研究机构最新报告，2026年全球云计算市场规模预计将达到8000亿美元，年复合增长率超过18%。与此同时，边缘计算作为云计算的延伸和补充，正成为行业新热点。</p><p>随着物联网设备数量的快速增长和实时数据处理需求的增加，边缘计算在智能制造、自动驾驶、智慧城市等领域的应用日益广泛。多家云服务商已推出边缘计算相关产品和服务。</p><p>分析人士认为，云边协同将成为未来计算架构的主流模式，企业需要构建云边端一体化的技术架构。</p>',
                'excerpt' => '全球云计算市场预计达8000亿美元，边缘计算作为新热点在智能制造、自动驾驶等领域广泛应用。',
                'cover' => '',
                'keywords' => '云计算,边缘计算,云边协同,物联网',
                'description' => '云计算市场持续增长，边缘计算成新热点，云边协同将成为未来主流计算架构。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 1,
                'flag_o' => 0,
                'like' => 132,
                'category_id' => 7,
                'author_id' => $authorId,
                'views' => 3500,
                'sort' => 3,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(10),
            ],
            [
                'title' => '数据安全法实施三周年，企业合规建设成效显著',
                'slug' => 'data-security-law-three-years',
                'content' => '<p>自《数据安全法》正式实施以来，已满三周年。三年来，我国数据安全治理体系不断完善，企业数据安全合规建设取得显著成效。</p><p>据统计，超过90%的大中型企业已建立数据安全管理制度，60%以上的企业设立了专门的数据安全岗位。在数据分类分级、安全评估、跨境数据流动管理等方面，企业合规水平持续提升。</p><p>专家表示，随着数字经济的深入发展，数据安全将面临更多新挑战，企业需要持续加强数据安全能力建设。</p>',
                'excerpt' => '数据安全法实施三周年，超90%大中企业已建立数据安全管理制度，合规建设成效显著。',
                'cover' => '',
                'keywords' => '数据安全法,合规建设,数据治理,信息安全',
                'description' => '数据安全法实施三周年回顾，企业数据安全合规建设成效显著。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 78,
                'category_id' => 7,
                'author_id' => $authorId,
                'views' => 1800,
                'sort' => 4,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(18),
            ],

            // ==================== 产品A系列 (category_id: 8) ====================
            [
                'title' => '智能数据分析平台V3.0正式发布',
                'slug' => 'smart-data-platform-v3-release',
                'content' => '<p>经过研发团队一年的精心打磨，智能数据分析平台V3.0于今日正式发布。新版本在数据处理能力、分析算法、用户体验等方面实现了全面升级。</p><p><strong>核心亮点：</strong></p><ul><li>数据处理速度提升300%，支持PB级数据实时分析</li><li>新增AI智能洞察功能，自动发现数据异常和趋势</li><li>可视化图表库扩容至200+种，满足各类业务场景</li><li>全新自然语言交互界面，降低数据分析门槛</li></ul><p>该平台已在金融、零售、制造等多个行业获得广泛应用，服务超过500家企业客户。</p>',
                'excerpt' => '智能数据分析平台V3.0发布，数据处理速度提升300%，新增AI智能洞察和自然语言交互功能。',
                'cover' => '',
                'keywords' => '数据分析,AI洞察,产品发布,V3.0',
                'description' => '智能数据分析平台V3.0正式发布，数据处理速度提升300%，新增AI智能洞察功能。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 1,
                'flag_o' => 1,
                'like' => 320,
                'category_id' => 8,
                'author_id' => $authorId,
                'views' => 8900,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(2),
            ],
            [
                'title' => '企业级云管理平台功能详解',
                'slug' => 'enterprise-cloud-management-platform',
                'content' => '<p>企业级云管理平台是公司核心产品之一，致力于帮助企业实现多云环境下的统一管理和运维。平台提供资源管理、监控告警、成本优化、安全合规等一站式解决方案。</p><p><strong>核心功能：</strong></p><ul><li>多云资源统一纳管：支持AWS、Azure、阿里云、腾讯云等主流云平台</li><li>智能运维：基于AI的故障预测和自动修复能力</li><li>成本优化：资源使用分析、闲置资源识别、成本优化建议</li><li>安全合规：多云安全态势感知、合规检查、安全审计</li></ul><p>目前该平台已管理超过10万台云服务器，为企业节省云成本平均达30%。</p>',
                'excerpt' => '企业级云管理平台功能详解，支持多云统一纳管，为企业节省云成本平均达30%。',
                'cover' => '',
                'keywords' => '云管理,多云管理,运维,成本优化',
                'description' => '企业级云管理平台功能介绍，支持多云统一管理、智能运维和成本优化。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 195,
                'category_id' => 8,
                'author_id' => $authorId,
                'views' => 5200,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(8),
            ],
            [
                'title' => '物联网设备管理平台行业应用案例分享',
                'slug' => 'iot-device-management-case-study',
                'content' => '<p>物联网设备管理平台上线以来，已在智慧城市、工业制造、能源管理等多个行业积累了丰富的应用案例。本文将分享几个典型应用场景。</p><p><strong>案例一：智慧城市路灯管理</strong>——某城市部署了超过5万盏智能路灯，通过平台实现远程监控、故障预警、节能策略配置，年节省电费超过200万元。</p><p><strong>案例二：工厂设备预测性维护</strong>——某制造企业利用平台对200余台关键设备进行实时监控，通过AI算法实现故障预测，设备故障率降低60%。</p><p><strong>案例三：能源管理优化</strong>——某园区通过平台管理800多个能源采集点，实现能耗实时监测和优化，年节能率达15%。</p>',
                'excerpt' => '物联网设备管理平台行业应用案例分享，涵盖智慧城市、工业制造、能源管理等场景。',
                'cover' => '',
                'keywords' => '物联网,设备管理,应用案例,智慧城市',
                'description' => '物联网设备管理平台在智慧城市、工业制造、能源管理等行业的应用案例分享。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 1,
                'flag_o' => 0,
                'like' => 145,
                'category_id' => 8,
                'author_id' => $authorId,
                'views' => 3800,
                'sort' => 3,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(12),
            ],

            // ==================== 产品B系列 (category_id: 9) ====================
            [
                'title' => '智能客服系统全新升级，支持多语言实时翻译',
                'slug' => 'smart-customer-service-upgrade',
                'content' => '<p>智能客服系统近日完成重大升级，新版本支持中文、英语、日语、韩语等12种语言的实时翻译，帮助企业实现全球化客户服务。</p><p><strong>新特性：</strong></p><ul><li>多语言实时翻译：客服对话自动翻译，打破语言壁垒</li><li>情感分析：实时识别客户情绪，辅助客服人员精准应对</li><li>知识库智能推荐：根据对话内容自动推荐相关知识条目</li><li>全渠道接入：支持网页、APP、微信、邮件等10+渠道</li></ul><p>升级后的智能客服系统已服务超过1000家企业，日均处理会话量突破500万次。</p>',
                'excerpt' => '智能客服系统全新升级，支持12种语言实时翻译，日均处理会话量突破500万次。',
                'cover' => '',
                'keywords' => '智能客服,多语言,实时翻译,情感分析',
                'description' => '智能客服系统全新升级，支持12种语言实时翻译和情感分析，服务超1000家企业。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 1,
                'flag_o' => 1,
                'like' => 280,
                'category_id' => 9,
                'author_id' => $authorId,
                'views' => 7500,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => '企业级协同办公套件功能介绍',
                'slug' => 'enterprise-collaboration-suite',
                'content' => '<p>企业级协同办公套件是面向中大型企业的一站式办公解决方案，涵盖即时通讯、文档协作、项目管理、视频会议、日程管理等核心功能。</p><p><strong>核心模块：</strong></p><ul><li>即时通讯：支持文字、语音、视频消息，消息已读回执，多端同步</li><li>文档协作：支持多人实时编辑，版本历史管理，权限控制</li><li>项目管理：看板、甘特图、任务分解、进度跟踪</li><li>视频会议：支持500人同时在线，屏幕共享，会议录制</li><li>日程管理：团队日历、会议室预定、日程提醒</li></ul><p>套件采用私有化部署方式，确保企业数据安全，已服务金融、政府、医疗等对数据安全要求高的行业客户。</p>',
                'excerpt' => '企业级协同办公套件功能介绍，涵盖即时通讯、文档协作、项目管理等核心模块。',
                'cover' => '',
                'keywords' => '协同办公,企业协作,项目管理,私有化部署',
                'description' => '企业级协同办公套件功能介绍，一站式办公解决方案，支持私有化部署。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 175,
                'category_id' => 9,
                'author_id' => $authorId,
                'views' => 4600,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(9),
            ],
            [
                'title' => '低代码开发平台助力企业数字化转型',
                'slug' => 'low-code-platform-digital-transformation',
                'content' => '<p>低代码开发平台是公司B系列产品线的重要组成部分，旨在帮助企业快速构建业务应用，加速数字化转型进程。</p><p><strong>平台优势：</strong></p><ul><li>拖拽式开发：无需编写代码，通过可视化组件即可搭建应用</li><li>丰富的模板库：提供100+行业模板，开箱即用</li><li>灵活扩展：支持自定义组件和API集成</li><li>多端适配：一次开发，自动适配PC、平板、手机</li><li>企业级特性：权限管理、数据安全、审计日志</li></ul><p>某零售企业使用该平台后，应用开发周期从平均45天缩短至7天，开发效率提升6倍以上。</p>',
                'excerpt' => '低代码开发平台助力企业数字化转型，应用开发周期从45天缩短至7天，效率提升6倍。',
                'cover' => '',
                'keywords' => '低代码,数字化转型,应用开发,可视化',
                'description' => '低代码开发平台介绍，帮助企业快速构建应用，加速数字化转型进程。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 1,
                'flag_o' => 0,
                'like' => 158,
                'category_id' => 9,
                'author_id' => $authorId,
                'views' => 4100,
                'sort' => 3,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(14),
            ],

            // ==================== 解决方案 (category_id: 3) ====================
            [
                'title' => '智慧园区整体解决方案',
                'slug' => 'smart-park-solution',
                'content' => '<p>针对产业园区管理痛点，公司推出智慧园区整体解决方案，利用物联网、大数据、AI等技术，实现园区运营管理的全面数字化和智能化。</p><p><strong>方案架构：</strong></p><ul><li>智能安防：人脸识别门禁、智能巡更、视频AI分析</li><li>智慧停车：车位引导、无感支付、车位预约</li><li>能耗管理：智能抄表、能耗分析、节能策略</li><li>智慧物业：在线报修、智能巡检、设备全生命周期管理</li><li>园区服务：企业服务、活动通知、访客管理</li></ul><p>该方案已在10余个产业园区落地应用，管理面积超过500万平方米，服务企业超2000家。</p>',
                'excerpt' => '智慧园区整体解决方案介绍，利用物联网、AI等技术实现园区运营全面数字化。',
                'cover' => '',
                'keywords' => '智慧园区,物联网,解决方案,数字化',
                'description' => '智慧园区整体解决方案，涵盖安防、停车、能耗、物业等核心模块。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 210,
                'category_id' => 3,
                'author_id' => $authorId,
                'views' => 5600,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(6),
            ],
            [
                'title' => '制造业数字化转型解决方案',
                'slug' => 'manufacturing-digital-transformation',
                'content' => '<p>面向制造业企业，公司提供从生产执行到供应链管理的全链路数字化转型解决方案。</p><p><strong>核心能力：</strong></p><ul><li>MES生产执行系统：生产过程实时监控、质量追溯、工艺管理</li><li>WMS仓储管理：智能入库、库位优化、拣货路径规划</li><li>设备管理：预测性维护、OEE分析、备件管理</li><li>供应链协同：需求预测、库存优化、供应商管理</li><li>数据看板：生产数据实时展示、异常预警、决策支持</li></ul><p>某汽车零部件企业应用该方案后，生产效率提升25%，库存周转率提高40%，质量不良率降低50%。</p>',
                'excerpt' => '制造业数字化转型解决方案，覆盖MES、WMS、设备管理等全链路，助力企业提质增效。',
                'cover' => '',
                'keywords' => '制造业,数字化转型,MES,WMS,智能制造',
                'description' => '制造业数字化转型解决方案，覆盖生产执行、仓储管理、供应链协同等核心环节。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 185,
                'category_id' => 3,
                'author_id' => $authorId,
                'views' => 4800,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(11),
            ],
            [
                'title' => '金融行业智能风控解决方案',
                'slug' => 'financial-intelligent-risk-control',
                'content' => '<p>针对金融行业日益复杂的风控需求，公司推出基于AI和大数据技术的智能风控解决方案。</p><p><strong>方案特色：</strong></p><ul><li>实时反欺诈：基于机器学习的实时交易风险识别，毫秒级响应</li><li>信用评估：多维度数据建模，精准评估用户信用风险</li><li>合规监测：自动化合规检查，监管报告自动生成</li><li>风险预警：多层级风险指标体系，智能预警和处置建议</li><li>模型管理：风控模型全生命周期管理，支持快速迭代优化</li></ul><p>该方案已服务于多家银行和保险机构，累计识别欺诈交易超过50万笔，挽回经济损失超过10亿元。</p>',
                'excerpt' => '金融行业智能风控解决方案，基于AI和大数据技术，累计识别欺诈交易超50万笔。',
                'cover' => '',
                'keywords' => '金融风控,反欺诈,信用评估,AI,大数据',
                'description' => '金融行业智能风控解决方案，覆盖实时反欺诈、信用评估、合规监测等核心场景。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 1,
                'flag_o' => 0,
                'like' => 198,
                'category_id' => 3,
                'author_id' => $authorId,
                'views' => 5100,
                'sort' => 3,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(16),
            ],

            // ==================== 关于我们 (category_id: 4) ====================
            [
                'title' => '公司简介',
                'slug' => 'company-introduction',
                'content' => '<p>公司成立于2015年，是一家专注于企业数字化转型的高新技术企业。公司总部位于深圳，在北京、上海、广州、成都等地设有分支机构。</p><p>公司拥有超过500人的专业团队，其中研发人员占比超过60%，核心团队来自国内外知名互联网企业和高校。公司累计获得软件著作权100余项，专利30余项。</p><p>公司秉承"技术驱动创新，服务创造价值"的理念，已为超过2000家企业客户提供数字化转型解决方案，覆盖金融、制造、零售、医疗、教育等多个行业。</p>',
                'excerpt' => '公司简介：成立于2015年，专注企业数字化转型，拥有500+专业团队，服务超2000家企业客户。',
                'cover' => '',
                'keywords' => '公司简介,企业介绍,数字化转型',
                'description' => '公司简介，成立于2015年的高新技术企业，专注企业数字化转型服务。',
                'code' => '',
                'flag_s' => 1,
                'flag_c' => 0,
                'flag_o' => 1,
                'like' => 95,
                'category_id' => 4,
                'author_id' => $authorId,
                'views' => 2500,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(30),
            ],
            [
                'title' => '企业文化与价值观',
                'slug' => 'company-culture-and-values',
                'content' => '<p><strong>企业使命：</strong>用科技赋能每一家企业，让数字化转型更简单。</p><p><strong>企业愿景：</strong>成为全球领先的企业数字化转型服务商。</p><p><strong>核心价值观：</strong></p><ul><li><strong>客户至上：</strong>始终以客户需求为导向，超越客户期望</li><li><strong>创新驱动：</strong>持续技术创新，引领行业发展</li><li><strong>团队协作：</strong>开放包容，合作共赢</li><li><strong>诚信务实：</strong>言行一致，说到做到</li><li><strong>追求卓越：</strong>精益求精，永不止步</li></ul><p>公司注重员工成长，建立了完善的培训体系和职业发展通道，定期组织团建活动和技能竞赛，营造积极向上的工作氛围。</p>',
                'excerpt' => '企业文化与价值观：客户至上、创新驱动、团队协作、诚信务实、追求卓越。',
                'cover' => '',
                'keywords' => '企业文化,价值观,使命愿景',
                'description' => '公司企业文化与价值观介绍，包括企业使命、愿景和核心价值观。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 65,
                'category_id' => 4,
                'author_id' => $authorId,
                'views' => 1200,
                'sort' => 2,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(25),
            ],

            // ==================== 联系我们 (category_id: 5) ====================
            [
                'title' => '联系我们',
                'slug' => 'contact-us',
                'content' => '<p>感谢您对我们公司的关注，如有任何业务咨询或合作需求，欢迎通过以下方式与我们联系。</p><p><strong>联系方式：</strong></p><ul><li>电话：400-888-8888</li><li>邮箱：contact@example.com</li><li>地址：深圳市南山区科技园路88号创新大厦18层</li><li>邮编：518000</li></ul><p><strong>工作时间：</strong></p><p>周一至周五 9:00-18:00（法定节假日除外）</p><p><strong>商务合作：</strong>business@example.com</p><p><strong>媒体联系：</strong>pr@example.com</p><p><strong>加入我们：</strong>hr@example.com</p>',
                'excerpt' => '联系我们：电话400-888-8888，邮箱contact@example.com，地址深圳市南山区科技园。',
                'cover' => '',
                'keywords' => '联系我们,联系方式,商务合作',
                'description' => '公司联系方式页面，提供电话、邮箱、地址等联系信息。',
                'code' => '',
                'flag_s' => 0,
                'flag_c' => 0,
                'flag_o' => 0,
                'like' => 30,
                'category_id' => 5,
                'author_id' => $authorId,
                'views' => 800,
                'sort' => 1,
                'status' => 1,
                'published_at' => Carbon::now()->subDays(60),
            ],
        ];

        $count = 0;
        foreach ($articles as $article) {
            $article['created_at'] = $now;
            $article['updated_at'] = $now;
            DB::table('content_articles')->insert($article);
            $count++;
        }

        $this->command->info("文章数据填充完成 (共 {$count} 条)");
    }
}