<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelSeeder extends Seeder
{
    /**
     * 填充模型装配数据（皮肤 + 骨骼部件）
     * 数据来源：renti/data-source/site-data.json -> model.skin / model.bones
     * 说明：运行时不读 json，数据已内嵌。at_json 为装配变换 JSON 数组。
     */
    public function run(): void
    {
        DB::table('model_parts')->truncate();

        $parts = [
            [
                'part_type' => 'skin',
                'name' => 'jss_Arm_L_Layer1',
                'obj' => 'female/skin/jss_Arm_L_Layer1__670.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Arm_L:Layer1","position":[-27.6707,111.9203,6.9874],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Arm_R_Layer1',
                'obj' => 'female/skin/jss_Arm_R_Layer1__702.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Arm_R:Layer1","position":[26.5273,110.8511,-10.1024],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Head_L_Layer1',
                'obj' => 'female/skin/jss_Head_L_Layer1__726.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Head_L:Layer1","position":[-4.551,159.1308,2.1397],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Head_R_Layer1',
                'obj' => 'female/skin/jss_Head_R_Layer1__762.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Head_R:Layer1","position":[4.4972,159.1308,2.1397],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Leg_L_Layer1',
                'obj' => 'female/skin/jss_Leg_L_Layer1__787.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Leg_L:Layer1","position":[-11.8276,48.3454,-8.2782],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Leg_R_Layer1',
                'obj' => 'female/skin/jss_Leg_R_Layer1__801.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Leg_R:Layer1","position":[10.2959,48.2639,11.3716],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Torso_L_Layer1',
                'obj' => 'female/skin/jss_Torso_L_Layer1__816.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Torso_L:Layer1","position":[-6.5018,116.4923,-0.9159],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Torso_L_Layer2',
                'obj' => 'female/skin/jss_Torso_L_Layer2__821.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Chest_L:Layer2","position":[-6.3666,130.8897,5.191],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Torso_R_Layer1',
                'obj' => 'female/skin/jss_Torso_R_Layer1__836.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Torso_R:Layer1","position":[6.2637,115.0855,-0.8708],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'skin',
                'name' => 'jss_Torso_R_Layer2',
                'obj' => 'female/skin/jss_Torso_R_Layer2__840.obj',
                'layer' => 'skin_f',
                'at_json' => '[{"go":"jss_Chest_R:Layer2","position":[6.458,130.9815,5.2272],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Arm_L_Layer2',
                'obj' => 'female/bones/jss_Arm_L_Layer2__683.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Arm_L:Layer2","position":[-27.6175,113.0518,7.7556],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Arm_L_Layer3',
                'obj' => 'female/bones/jss_Arm_L_Layer3__693.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Arm_L:Layer3","position":[-32.7979,95.9428,12.2477],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Arm_R_Layer2',
                'obj' => 'female/bones/jss_Arm_R_Layer2__710.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Arm_R:Layer2","position":[26.6747,111.5739,-10.4902],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Arm_R_Layer3',
                'obj' => 'female/bones/jss_Arm_R_Layer3__718.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Arm_R:Layer3","position":[30.6577,94.335,-17.8552],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_L_Layer2',
                'obj' => 'female/bones/jss_Head_L_Layer2__734.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_L:Layer2","position":[-1.2353,156.8396,7.619],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_L_Layer3',
                'obj' => 'female/bones/jss_Head_L_Layer3__742.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_L:Layer3","position":[-3.5009,163.0301,1.6619],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_L_Layer4',
                'obj' => 'female/bones/jss_Head_L_Layer4__749.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_L:Layer4","position":[-1.6404,153.8784,-2.2624],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_L_Layer5',
                'obj' => 'female/bones/jss_Head_L_Layer5__756.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_L:Layer5","position":[-0.804,154.4627,3.3342],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_R_Layer2',
                'obj' => 'female/bones/jss_Head_R_Layer2__767.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_R:Layer2","position":[1.2718,156.8396,7.619],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_R_Layer3',
                'obj' => 'female/bones/jss_Head_R_Layer3__772.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_R:Layer3","position":[3.5486,163.0301,1.6619],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_R_Layer4',
                'obj' => 'female/bones/jss_Head_R_Layer4__777.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_R:Layer4","position":[1.7606,153.8784,-2.2665],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Head_R_Layer5',
                'obj' => 'female/bones/jss_Head_R_Layer5__782.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Head_R:Layer5","position":[0.8916,154.4656,3.2942],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Leg_L_Layer2',
                'obj' => 'female/bones/jss_Leg_L_Layer2__792.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Leg_L:Layer2","position":[-14.4499,47.4464,-9.1463],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Leg_L_Layer3',
                'obj' => 'female/bones/jss_Leg_L_Layer3__796.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Leg_L:Layer3","position":[-16.6606,4.367,-18.0834],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Leg_R_Layer2',
                'obj' => 'female/bones/jss_Leg_R_Layer2__806.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Leg_R:Layer2","position":[12.5044,47.9645,12.892],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Leg_R_Layer3',
                'obj' => 'female/bones/jss_Leg_R_Layer3__811.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Leg_R:Layer3","position":[13.9873,4.3301,14.385],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Torso_L_Layer3',
                'obj' => 'female/bones/jss_Torso_L_Layer3__826.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Torso_L:Layer3","position":[-8.071,116.604,0.3599],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Torso_L_Layer4',
                'obj' => 'female/bones/jss_Torso_L_Layer4__831.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Torso_L:Layer4","position":[-1.6965,126.4552,-4.2187],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Torso_R_Layer3',
                'obj' => 'female/bones/jss_Torso_R_Layer3__844.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Torso_R:Layer3","position":[8.2843,116.5894,0.3414],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
            [
                'part_type' => 'bones',
                'name' => 'jss_Torso_R_Layer4',
                'obj' => 'female/bones/jss_Torso_R_Layer4__848.obj',
                'layer' => 'inner',
                'at_json' => '[{"go":"jss_Torso_R:Layer4","position":[1.8232,126.4629,-4.2187],"quat":[0,0,0,1],"scale":[1,1,1]}]',
                'sort' => 0,
                'status' => 1,
            ],
        ];

        DB::table('model_parts')->insert($parts);
    }
}
